routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'CheckRole:admin']], function () {
    Route::resource('pelatihan', 'PelatihanController');
    // Route::post('pelatihan/{pelatihan}/update', 'PelatihanController@updatedata')->name('updatedata');
    Route::resource('jabatan', 'JabatanController');
    Route::get('pegawai/{id}/hapus', 'PegawaiController@hapus_data');
    Route::resource('pegawai', 'PegawaiController')->except('show');
    Route::resource('peserta', 'PesertaController');
    // Route::post('rekapitulasi/simpan_sementara', 'RekapController@simpan_sementara')->name('rekapitulasi.simpan_sementara');
    Route::get('penilaian/detail', 'PenilaianController@detail_index')->name('penilaian.detail_index');
    Route::get('penilaian/detail/create', 'PenilaianController@detail_create')->name('penilaian.detail_create');
    Route::post('penilaian/detail', 'PenilaianController@detail_store')->name('penilaian.detail_store');
    Route::resource('penilaian', 'PenilaianController');
    Route::get('penilaian/detail/{penilaian}/delete', 'PenilaianController@hapus')->name('penilaian.nilai_hapus');
    Route::get('penilaian/{penilaian}/hapus', 'PenilaianController@hapus_penilaian')->name('penilaian.hapus_penilaian');
    // Route::post('rekapitulasi/update_sementara', 'RekapController@update_sementara')->name('rekapitulasi.update_sementara');
    Route::post('pelatihan/import', 'PelatihanController@import')->name('pelatihan.import');
    Route::resource('agama', 'AgamaController');
    Route::get('pangkat', 'PangkatController@index')->name('pangkat.index');
    Route::get('pangkat/create', 'PangkatController@create')->name('pangkat.create');
    Route::post('pangkat', 'PangkatController@store')->name('pangkat.store');
    Route::delete('pangkat/{pangkat}', 'PangkatController@destroy')->name('pangkat.destroy');
    Route::resource('jenis', 'JenisController');
    Route::resource('lokasi', 'LokasiController');
    // Route::get('/home', 'DashboardController@dashboard')->name('home');
});

Route::group(['middleware' => ['auth', 'CheckRole:admin,staff']], function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-detail','RekapController@nama_penilaian_detail')->name('rekapitulasi.nama_penilaian_detail');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-ket','RekapController@ket_penilaian_detail')->name('rekapitulasi.ket_penilaian_detail');
    Route::get('rekapitulasi/create_nilai', 'RekapController@create_nilai')->name('rekapitulasi.create_nilai');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}', 'RekapController@data_peserta')->name('rekapitulasi.data_peserta');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}/nilai', 'RekapController@data_peserta_show')->name('rekapitulasi.data_peserta_show');
    Route::post('rekapitulasi/simpan_rekap', 'RekapController@simpan_rekap')->name('rekapitulasi.simpan_rekap');
    Route::resource('rekapitulasi', 'RekapController');
    Route::get('laporan/peserta', 'RekapController@index_peserta')->name('rekapitulasi.index_peserta');
    Route::get('laporan', 'RekapController@laporan_index')->name('rekapitulasi.laporan_index');
    Route::get('laporan/peserta/{laporan}/', 'RekapController@laporan')->name('rekapitulasi.laporan');
    Route::get('laporan/pelatihan/{id}/download', 'RekapController@export_pelatihan')->name('rekapitulasi.exportpelatihan');
    Route::get('laporan/{id}/download', 'RekapController@export')->name('rekapitulasi.export');
    Route::post('rekapitulasi/{rekapitulasi}/editnilai', 'ApiController@editnilai');
});

resources/views/rekapitulasi/create.blade.php
@extends('layouts.template')

@section('css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

@endsection
@section('content')
    <h2 class="h3 mb-4 text-gray-800">Input Penilaian Peserta</h2>
    <div class="row">
        <div class="col-md-6">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('rekapitulasi.index')}}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                  <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Kembali</span>
              </a>
            </div>
            <div class="card-body">
                <form action="{{ route('rekapitulasi.store') }}" method="POST" class="form-horizontal">
                @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <select name="id_penilaian_induk" id="id_penilaian_induk" class="form-control" >
                                @foreach($list_penilaian_induk as $induk)
                                    <option value="{{ $induk->id_penilaian_induk }}">{{ $induk->nama_penilaian_induk }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <select name="id_penilaian_detail" id="id_penilaian_detail" class="form-control" >
                                @foreach($list_penilaian_detail as $detail)
                                    <option value="{{ $detail->id_penilaian_detail }}">{{ $detail->nama_penilaian_detail }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <select name="id_peserta" id="id_peserta" class="form-control" id="id_peserta" >
                                @foreach($list_peserta as $peserta)
                                    <option value="{{ $peserta->id_peserta }}">{{ $peserta->pelatihan->nama_pelatihan }} - {{ $peserta->nama_peserta }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <select name="id_pegawai" id="id_pegawai" class="form-control" >
                                @foreach($list_pegawai as $pegawai)
                                    <option value="{{ $pegawai->id_pegawai }}">{{ $pegawai->nama_pegawai }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="number" name="nilai" class="form-control" minlength="2" maxlength="3" pattern="[0-9]*" placeholder="Nilai Peserta (cth: 90)" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <textarea type="text" class="form-control" name="ket" placeholder="Keterangan" rows="5"></textarea>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary mb-2">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_peserta').select2();
        })
    </script>
@endsection

resources/views/rekapitulasi/create_nilai.blade.php
@extends('layouts.template')

@section('css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Input Nilai Peserta Pelatihan</h2>
    <div class="row">
        <div class="col-md-12">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Pilih Kelas</h6>
              {{-- <a href="{{ route('rekapitulasi.index')}}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                  <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Kembali</span>
              </a> --}}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-light" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                        <th width="5%">No.</th>
                        <th>Pelatihan</th>
                        <th>Tgl Mulai</th>
                        <th>Tgl Akhir</th>
                        <th>Kuota</th>
                        <th>Jenis</th>
                        <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($list_pelatihan as $pelatihan)
                        <tr>
                            <th>{{ $loop->iteration }}</th>
                            <th>{{ $pelatihan->nama_pelatihan }}</th>
                            <th>{{ \Carbon\Carbon::parse($pelatihan->tgl_mulai)->locale('id')->isoFormat('LL') }}</th>
                            <th>{{ \Carbon\Carbon::parse($pelatihan->tgl_akhir)->locale('id')->isoFormat('LL') }}</th>
                            <th>{{ $pelatihan->kuota }}</th>
                            <th>{{ $pelatihan->jenis->jenis_pelatihan }}</th>
                            <th>
                                <a href="{{ route('rekapitulasi.show', $pelatihan->id_pelatihan) }}" class='btn btn-sm btn-danger'>Pilih Kelas</a>
                            </th>
                        </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
            </div>
          </div>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_peserta').select2();
        })
    </script>
@endsection

resources/views/rekapitulasi/data_nilai.blade.php
@extends('layouts.template')

@section('css')
  <!-- Custom styles for this page -->
  <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<h2 class="h3 mb-4 text-gray-800">Daftar Nama Peserta by Kelas</h2>
    <div class="row">
        <div class="col-md-12">
            <!-- Basic Card Example -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Kelas : {{ $list_pelatihan->nama_pelatihan }}</h6>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <a href="{{ route('rekapitulasi.index')}}" class="btn btn-primary btn-icon-split">
                          <span class="icon text-white-50">
                            <i class="fas fa-arrow-left"></i>
                          </span>
                          <span class="text">Kembali</span>
                        </a>
                    </div>
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th width="5%">No.</th>
                        <th>Nama Peserta</th>
                        <th>NIP</th>
                        <th>JK</th>
                        <th>Instansi</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($list_peserta as $peserta)
                        <tr>
                          <th>{{ $loop->iteration }}</th>
                          <th>{{ $peserta->nama_peserta }}</th>
                          <th>{{ $peserta->nip }}</th>
                          <th>{{ $peserta->jk }}</th>
                          <th>{{ $peserta->instansi }}</th>
                          <th>
                              <a href="{{ url('rekapitulasi/data_peserta/'.$peserta->id_peserta.'/nilai') }}" class='btn btn-sm btn-success'>Lihat Nilai</a>
                          </th>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
        </div>
    </div>
@endsection

@section('js')
    <!-- Page level plugins -->
  <script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('template/js/demo/datatables-demo.js') }}"></script>
@endsection

resources/views/rekapitulasi/edit.blade.php
@extends('layouts.template')

@section('css')
    <link href="{{ asset('css/bootstrap-editable.css') }}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <!-- Custom styles for this page -->
    <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
{{-- <h2 class="h3 mb-4 text-gray-800">Input Nilai Peserta</h2> --}}
    <div class="row">
        <div class="col-lg-6 col-xs-12">
            <!-- Basic Card Example -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Data Peserta</h6>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label col-sm-12">Kelas</label>
                        <div class="col-sm-12">
                            <input type="text" name="tempat_lahir" class="form-control" value="{{ $list_peserta[0]->nama_pelatihan }}" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">Nama Peserta</label>
                        <div class="col-sm-12">
                            <input type="text" name="nama_peserta" class="form-control" value="{{ $list_peserta[0]->nama_peserta }}" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">Instansi</label>
                        <div class="col-sm-12">
                            <input type="text" name="instansi" class="form-control" readonly value="{{ $list_peserta[0]->instansi }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">NIP</label>
                        <div class="col-sm-12">
                            <input type="text" name="nip" class="form-control" value="{{ $list_peserta[0]->nip }}" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">Alamat</label>
                        <div class="col-sm-12">
                            <textarea type="text" name="alamat" class="form-control" rows="4" readonly>{{ $list_peserta[0]->alamat }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                </div>
              </div>
        </div>
        <div class="col-lg-6 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Input Nilai Peserta</h6>
                </div>
                <div class="card-body">
                <form class="form-horizontal" method="post" action="{{ route('rekapitulasi.simpan_rekap') }}">
                @csrf
                    <input type="hidden" name="id_jenis" value="{{ $list_peserta[0]->id_jenis }}">
                    <input type="hidden" name="id_lokasi" value="{{ $list_peserta[0]->id_lokasi }}">
                    <input type="hidden" name="id_peserta" value="{{ $list_peserta[0]->id_peserta }}">
                    <div class="form-group">
                        <label class="control-label col-sm-6">Widyaiswara yang memberi nilai <span class="text-danger" title="This field is required">*</span></label>
                        <div class="col-sm-12">
                            <select name="id_pegawai" id="id_pegawai" class="form-control datawi">
                                <option disable="true" selected="true" required>=== Pilih Widyaiswara ===</option>
                                @foreach($list_wi as $in => $value)
                                    <option value="{{ $value['id_pegawai'] }}">{{ $value['nama_pegawai'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">Penilaian Induk <span class="text-danger" title="This field is required">*</span></label>
                        <div class="col-sm-12">
                            <select name="penilaian_induk" id="penilaian_induk" class="form-control">
                                <option value="" disable="true" selected="true" required>=== Pilih Penilaian Utama ===</option>
                                @foreach($list_penilaian_induk as $in => $value)
                                    <option value="{{ $value['id_penilaian_induk'] }}">{{ $value['nama_penilaian_induk'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-12">Unsur Penilaian Detail <span class="text-danger" title="This field is required">*</span></label>
                        <div class="col-sm-12">
                            <select name="id_penilaian_detail" id="id_penilaian_detail" class="form-control">
                                    <option value=""  disable="true" selected="true" required>=== Pilih Unsur Penilaian Detail ===</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                        <label for="garis">Input Nilai</label><br>
                            <input type="text" minlength="2" maxlength="3" pattern="[0-9]*" name="nilai_detail" value="{{ old('nilai_detail')}}" placeholder="Masukkan Nilai (cth: 90)" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <h4 name="ket_penilaian_detail" id="ket_penilaian_detail" for="ket_penilaian_detail"></h4>
                        {{-- <label for="garis">=======</label><br> --}}
                        </div>
                    </div>
                </div>
                 <div class="card-footer">
                    <a href="{{ route('rekapitulasi.show', $list_peserta[0]->id_pelatihan) }}" class="btn btn-lg btn-secondary float-right">
                        <span class="icon text-white-50"></i></span><span class="text">Kembali</span>
                    </a>
                    <input type="submit" name="submit" value="Proses" class="btn btn-lg btn-success">
                </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Data Unsur Penilaian</h6>
                </div>
                <div class="card-body py3">
                    <table id="dataNilai" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th width="5%">No.</th>
                                <th width="20%">Unsur Penilaian Induk</th>
                                <th width="30%">Unsur Penilaian Detail</th>
                                <th width="35%">Nama Penilaian Detail</th>
                                <th width="10%">Nilai</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($list_detail as $list)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $list->nama_penilaian_induk }}</td>
                                <td>{{ $list->nama_penilaian_detail }}</td>
                                <td>{{ $list->ket }}</td>
                                <td><a href="#" class="nilai" data-type="number" data-name="{{ $list->id_penilaian_detail }}" data-pk="{{ $list->id_rekap }}" data-url="/rekap/api/rekapitulasi/{{ $list->id_rekap }}/editnilai" data-title="Masukan nilai terbaru">{{ $list->nilai_detail }}</a></td>
                                <td>
                                    <form class="delete-btn" nama-detail="{{ $list->nama_penilaian_detail }}" method="POST" action="{{ route('rekapitulasi.destroy', [$list->id_rekap]) }}">
                                        @csrf
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="btn btn-sm btn-danger delete-btn"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <!-- Page level plugins -->
    <script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
        $('#dataNilai').DataTable( {
            "scrollX": true
            } );
        });
    </script>
    <script>
        $(document).ready(function() {
            $('.datawi').select2();
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.12.0/dist/sweetalert2.all.min.js"></script>
    <script>
        $('.delete-btn').on('click', function(e) {
            e.preventDefault();
            var self = $(this);
            var nama_detail = $(this).attr('nama-detail');
            Swal.fire({
                title: 'Data akan dihapus?',
                text: "PENILAIAN : "+ nama_detail +"",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Hapus!'
            }).then((result) => {
                if (result.value) {
                    $('.delete-btn').submit();
                }
            })
        });
    </script>
    <script src="{{ asset('js/bootstrap-editable.min.js') }}"></script>
    {{-- <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script> --}}
    <script type="text/javascript">
        $('#penilaian_induk').on('change', function(e){
          console.log(e);
          var id_penilaian_induk = e.target.value;
          $.get('edit/json-detail?id_penilaian_induk=' + id_penilaian_induk,function(data) {
            console.log(data);
            $('#id_penilaian_detail').empty();
            $('#id_penilaian_detail').append('<option value="0" disable="true" selected="true">=== Select Unsur Penilaian ===</option>');

            $.each(data, function(index, id_penilaian_detailObj){
              $('#id_penilaian_detail').append('<option value="'+ id_penilaian_detailObj.id_penilaian_detail +'">'+ id_penilaian_detailObj.nama_penilaian_detail +'</option>');
            })
          });
        });

        $('#id_penilaian_detail').on('change', function(e){
          console.log(e);
          var id_penilaian_detail = e.target.value;
          $.get('edit/json-ket?id_penilaian_detail=' + id_penilaian_detail,function(data) {
            console.log(data);
            $('#ket_penilaian_detail').empty();
            $('#ket_penilaian_detail').append('<label></label>');

            $.each(data, function(index, id_penilaian_detailObj){
              $('#ket_penilaian_detail').append('<h4>'+ id_penilaian_detailObj.ket +'</h4>');
            })
          });
        });

        $(document).ready(function() {
            $('.nilaia').editable();
        });
        $(document).ready(function() {
            $('.nilai').editable({ type:'input', tpl: '<input type="number" onKeyPress="if(this.value.length==4) return false;" minlength="2" maxlength="3" min="60" max="100" pattern="[0-9]*" required>' });
        });
    </script>
@endsection

resources/views/rekapitulasi/index.blade.php
@extends('layouts.template')

@section('css')
<!-- Custom styles for this page -->
  <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Data Penilaian Induk</h2>
    <div class="row">
        <div class="col-md-12">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
                <a href="{{ route('rekapitulasi.create')}}" class="btn btn-primary btn-icon-split">
                  <span class="icon text-white-50">
                    <i class="fas fa-arrow-right"></i>
                  </span>
                  <span class="text">Input Penilaian</span>
                </a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th rowspan="3" style="text-align: center; vertical-align: middle;">No</th>
                            <th rowspan="2" style="text-align: center; vertical-align: middle;">Nama</th>
                            <th colspan="2" style="text-align: center; vertical-align: middle;">A1<br>(15%)</th>
                            <th style="text-align: center; vertical-align: middle;">Z1</th>
                            <th colspan="2" style="text-align: center; vertical-align: middle;">A2<br>(20%)</th>
                            <th style="text-align: center; vertical-align: middle;">Z1</th>
                            <th colspan="4" style="text-align: center; vertical-align: middle;">A3<br>(20%)</th>
                            <th style="text-align: center; vertical-align: middle;">Z1</th>
                            <th colspan="4" style="text-align: center; vertical-align: middle;">A4<br>(30 %)</th>
                            <th style="text-align: center; vertical-align: middle;">Z1</th>
                            <th colspan="2" style="text-align: center; vertical-align: middle;">A5<br>(15%)</th>
                            <th style="text-align: center; vertical-align: middle;">Kualifikasi</th>
                            <th style="text-align: center; vertical-align: middle;">Peringkat</th>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>1</td>
                            <td>3</td>
                            <td>4</td>
                            <td>1</td>
                            <td>5</td>
                            <td>6</td>
                            <td>7</td>
                            <td>8</td>
                            <td>1</td>
                            <td>9</td>
                            <td>10</td>
                            <td>11</td>
                            <td>12</td>
                            <td>1</td>
                            <td>13</td>
                            <td>14</td>
                            <td>15</td>
                            <td>16</td>
                        </tr>
                        </thead>
                        <tbody>
                          @foreach($list_rekap as $rekap)
                          <tr>
                            <th>{{ $loop->iteration ?? '' }}</th>
                            <th>{{ $rekap->peserta->nama_peserta }}</td>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>{{ $rekap->nilai }}</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                          </tr>
                          @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('js')
    <!-- Page level plugins -->
  <script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
  <!-- Page level custom scripts -->
  <script src="{{ asset('template/js/demo/datatables-demo.js') }}"></script>
@endsection