routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'CheckRole:admin']], function () {
    Route::resource('pelatihan', 'PelatihanController');
    // Route::post('pelatihan/{pelatihan}/update', 'PelatihanController@updatedata')->name('updatedata');
    Route::resource('jabatan', 'JabatanController');
    Route::get('pegawai/{id}/hapus', 'PegawaiController@hapus_data');
    Route::resource('pegawai', 'PegawaiController')->except('show');
    Route::resource('peserta', 'PesertaController');
    // Route::post('rekapitulasi/simpan_sementara', 'RekapController@simpan_sementara')->name('rekapitulasi.simpan_sementara');
    Route::get('penilaian/detail', 'PenilaianController@detail_index')->name('penilaian.detail_index');
    Route::get('penilaian/detail/create', 'PenilaianController@detail_create')->name('penilaian.detail_create');
    Route::post('penilaian/detail', 'PenilaianController@detail_store')->name('penilaian.detail_store');
    Route::resource('penilaian', 'PenilaianController');
    Route::get('penilaian/detail/{penilaian}/delete', 'PenilaianController@hapus')->name('penilaian.nilai_hapus');
    Route::get('penilaian/{penilaian}/hapus', 'PenilaianController@hapus_penilaian')->name('penilaian.hapus_penilaian');
    // Route::post('rekapitulasi/update_sementara', 'RekapController@update_sementara')->name('rekapitulasi.update_sementara');
    Route::post('pelatihan/import', 'PelatihanController@import')->name('pelatihan.import');
    Route::resource('agama', 'AgamaController');
    Route::get('pangkat', 'PangkatController@index')->name('pangkat.index');
    Route::get('pangkat/create', 'PangkatController@create')->name('pangkat.create');
    Route::post('pangkat', 'PangkatController@store')->name('pangkat.store');
    Route::delete('pangkat/{pangkat}', 'PangkatController@destroy')->name('pangkat.destroy');
    Route::resource('jenis', 'JenisController');
    Route::resource('lokasi', 'LokasiController');
    // Route::get('/home', 'DashboardController@dashboard')->name('home');
});

Route::group(['middleware' => ['auth', 'CheckRole:admin,staff']], function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-detail','RekapController@nama_penilaian_detail')->name('rekapitulasi.nama_penilaian_detail');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-ket','RekapController@ket_penilaian_detail')->name('rekapitulasi.ket_penilaian_detail');
    Route::get('rekapitulasi/create_nilai', 'RekapController@create_nilai')->name('rekapitulasi.create_nilai');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}', 'RekapController@data_peserta')->name('rekapitulasi.data_peserta');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}/nilai', 'RekapController@data_peserta_show')->name('rekapitulasi.data_peserta_show');
    Route::post('rekapitulasi/simpan_rekap', 'RekapController@simpan_rekap')->name('rekapitulasi.simpan_rekap');
    Route::resource('rekapitulasi', 'RekapController');
    Route::get('laporan/peserta', 'RekapController@index_peserta')->name('rekapitulasi.index_peserta');
    Route::get('laporan', 'RekapController@laporan_index')->name('rekapitulasi.laporan_index');
    Route::get('laporan/peserta/{laporan}/', 'RekapController@laporan')->name('rekapitulasi.laporan');
    Route::get('laporan/pelatihan/{id}/download', 'RekapController@export_pelatihan')->name('rekapitulasi.exportpelatihan');
    Route::get('laporan/{id}/download', 'RekapController@export')->name('rekapitulasi.export');
    Route::post('rekapitulasi/{rekapitulasi}/editnilai', 'ApiController@editnilai');
});

app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    protected $table = "pegawai";
    protected $primaryKey = "id_pegawai";
    protected $fillable = [
        'nama_pegawai','nip', 'tempat_lahir', 'tgl_lahir','jk','unit_kerja', 'instansi', 'id_pangkat', 'id_jabatan'
    ];
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Pegawai;
use App\Pangkat;
use App\Jabatan;
use Validator;
use Illuminate\Http\Request;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_pegawai = Pegawai::all();
        return view ('setting.pegawai.index',[
            'list_pegawai' => $list_pegawai,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $list_pegawai = Pegawai::all();
        $list_pangkat = Pangkat::all();
        $list_jabatan = Jabatan::all();
        return view ('setting.pegawai.create',[
            'list_pegawai' => $list_pegawai,
            'list_pangkat' => $list_pangkat,
            'list_jabatan' => $list_jabatan,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validasi = Validator::make($input, [
            'nama_pegawai' => 'required|min:4|max:100',
            'nip' => 'required|numeric',
            'tempat_lahir' => 'required|max:100',
            'tgl_lahir' => 'required|date',
            'jk' => 'required',
            'unit_kerja' => 'required|max:100',
            'instansi' => 'required|max:100',
            'id_pangkat' => 'required|numeric',
            'id_jabatan' => 'required|numeric',
        ]);

        if ($validasi->fails()) {
            return back()->with('warning', $validasi->messages()->all()[0])->withInput();
        }

        // return $input;
        Pegawai::create($input);
        return redirect()->route('pegawai.index')->with('toast_success','Data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pegawai = Pegawai::findOrFail($id);
        $list_pangkat = Pangkat::all();
        $list_jabatan = Jabatan::all();
        return view ('setting.pegawai.edit', compact('pegawai', 'list_pangkat', 'list_jabatan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // return $request->all();
        $input = $request->all();

        $validasi = Validator::make($input, [
            'nama_pegawai' => 'required|min:4|max:100',
            'nip' => 'required|numeric',
            'tempat_lahir' => 'required|max:100',
            'tgl_lahir' => 'required|date',
            'jk' => 'required',
            'unit_kerja' => 'required|max:100',
            'instansi' => 'required|max:100',
            'id_pangkat' => 'required|numeric',
            'id_jabatan' => 'required|numeric',
        ]);

        if ($validasi->fails()) {
            return back()->with('warning', $validasi->messages()->all()[0])->withInput();
        }

        // return $input;
        $data = Pegawai::findOrFail($id);
        $data->nama_pegawai = $request->nama_pegawai;
        $data->nip = $request->nip;
        $data->tempat_lahir = $request->tempat_lahir;
        $data->tgl_lahir = $request->tgl_lahir;
        $data->jk = $request->jk;
        $data->instansi = $request->unit_kerja;
        $data->id_pangkat = $request->id_pangkat;
        $data->id_jabatan = $request->id_jabatan;
        $data->save();

        return redirect()->route('pegawai.index')->with('toast_success','Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // return $id;
        // $pegawai_id = Pegawai::find($id);
        // $pegawai_id->delete();
        // return redirect()->back()->with('toast_success', "Data berhasil dihapus");
    }


    public function hapus_data($id)
    {
        // return $id;
        $pegawai_id = Pegawai::find($id);
        $pegawai_id->delete();
        return redirect()->back()->with('toast_success', "Data berhasil dihapus");
    }
}

resources/views/setting/pegawai/create.blade.php
@extends('layouts.template')

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Input Pegawai</h2>
    <div class="row">
        <div class="col-md-6">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('pegawai.index')}}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Kembali</span>
                  </a>
            </div>
            <div class="card-body">
                <form action="{{ route('pegawai.store') }}" method="POST" class="form-horizontal">
                @csrf
                    <div class="row">
                        <div class="col-md-12">
                        <label for="">Nama Pegawai</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="nama_pegawai" placeholder="Cth : Abdullah" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">NIP</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="nip" minlength="18" maxlength="18" pattern="[0-9]*" placeholder="NIP Pegawai" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Jenis Kelamin</label><span class="text-danger"> *</span>
                            <select name="jk" id="jk" class="form-control">
                                <option value="L">Laki-Laki</option>
                                <option value="P">Perempuan</option>
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Pangkat/Golongan</label><span class="text-danger"> *</span>
                            <select name="id_pangkat" id="id_pangkat" class="form-control">
                                @foreach($list_pangkat as $pangkat)
                                    <option value="{{ $pangkat->id }}">{{ $pangkat->nama_pangkat }} ({{ $pangkat->golongan }})</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Jabatan</label><span class="text-danger"> *</span>
                            <select name="id_jabatan" id="id_pangkat" class="form-control">
                                @foreach($list_jabatan as $jabatan)
                                    <option value="{{ $jabatan->id_jabatan }}">{{ $jabatan->nama_jabatan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Tempat Lahir</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="tempat_lahir" placeholder="Tempat Lahir (cth: Kutai Kartanegara)" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Tgl Lahir</label><span class="text-danger"> *</span>
                            <input type="date" class="form-control" name="tgl_lahir" placeholder="Tgl Lahir" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Unit Kerja</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="unit_kerja" placeholder="Unit Kerja" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Instansi</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="instansi" placeholder="Instansi Induk" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary mb-2">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

resources/views/setting/pegawai/edit.blade.php
@extends('layouts.template')

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Input Pegawai</h2>
    <div class="row">
        <div class="col-md-6">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('pegawai.index')}}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Kembali</span>
                  </a>
            </div>
            <div class="card-body">
                <form action="{{ route('pegawai.update', [$pegawai->id_pegawai]) }}" method="POST" class="form-horizontal">
                @csrf
                @method('put')
                    <div class="row">
                        <div class="col-md-12">
                        <label for="">Nama Pegawai</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="nama_pegawai" placeholder="Cth : Abdullah" value="{{ $pegawai->nama_pegawai }}" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">NIP</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="nip" minlength="18" maxlength="18" pattern="[0-9]*" value="{{ $pegawai->nip }}"placeholder="NIP Pegawai" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Jenis Kelamin</label><span class="text-danger"> *</span>
                            <select name="jk" id="jk" class="form-control">
                                <option value="L">Laki-Laki</option>
                                <option value="P">Perempuan</option>
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Pangkat/Golongan</label><span class="text-danger"> *</span>
                            <select name="id_pangkat" id="id_pangkat" class="form-control">
                                @foreach($list_pangkat as $pangkat)
                                    <option value="{{ $pangkat->id }}"@if($pegawai->id_pangkat == $pangkat->id) Selected @endif>{{ $pangkat->nama_pangkat }} ({{ $pangkat->golongan }})</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Jabatan</label><span class="text-danger"> *</span>
                            <select name="id_jabatan" id="id_pangkat" class="form-control">
                                @foreach($list_jabatan as $jabatan)
                                    <option value="{{ $jabatan->id_jabatan }}"@if($pegawai->id_jabatan == $jabatan->id_jabatan) Selected @endif>{{ $jabatan->nama_jabatan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Tempat Lahir</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="tempat_lahir" value="{{ $pegawai->tempat_lahir }}" placeholder="Tempat Lahir (cth: Kutai Kartanegara)" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Tgl Lahir</label><span class="text-danger"> *</span>
                            <input type="date" class="form-control" name="tgl_lahir" value="{{ $pegawai->tgl_lahir }}" placeholder="Tgl Lahir" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Unit Kerja</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="unit_kerja" value="{{ $pegawai->unit_kerja }}" placeholder="Unit Kerja" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Instansi</label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" name="instansi" value="{{ $pegawai->instansi }}" placeholder="Instansi Induk" required>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary mb-2">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

resources/views/setting/pegawai/index.blade.php
@extends('layouts.template')

@section('css')
  <!-- Custom styles for this page -->
  <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Data Pegawai</h2>
    <div class="row">
        <div class="col-md-12">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('pegawai.create')}}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
                    <span class="text">Tambah Data</span>
                  </a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered table-hover" id="pegawai" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th width="5%">No.</th>
                      <th width="30%">Nama</th>
                      <th>NIP</th>
                      <th>JK</th>
                      <th>Tempat, Tgl Lahir</th>
                      <th width="10%">Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach($list_pegawai as $pegawai)
                        <tr>
                            <th>{{ $loop->iteration }}</th>
                            <th>{{ $pegawai->nama_pegawai }}</th>
                            <th>{{ $pegawai->nip }}</th>
                            <th>{{ $pegawai->jk }}</th>
                            <th>{{ $pegawai->tempat_lahir }}, {{ \Carbon\Carbon::parse($pegawai->tgl_lahir)->locale('id')->isoFormat('LL') }}</th>
                            <th>
                                <a href="{{ action('PegawaiController@hapus_data', [$pegawai->id_pegawai])}}" nama-detail="{{ $pegawai->nama_pegawai }}" class="btn btn-danger btn-sm delete-confirm"><i class="fas fa-trash"></i></a>
                                <a href="{{ route('pegawai.edit', [$pegawai->id_pegawai]) }}" class="btn btn-sm btn-info"><i class='fa fa-magic'></i></a>
                            </th>
                        </tr>
                        @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('js')
  <script>
    $('.delete-confirm').on('click', function (event) {
        event.preventDefault();
        const url = $(this).attr('href');
        var nama_detail = $(this).attr('nama-detail');
        swal({
            title: 'Data akan dihapus?',
            text: "'"+ nama_detail +"' akan dihapus?",
            icon: 'warning',
            buttons: ["Cancel", "Yes!"],
        }).then(function(value) {
            if (value) {
                window.location.href = url;
            }
        });
    });
  </script>
  <script>
      $(document).ready(function() {
      $('#pegawai').DataTable( {
          "scrollX": true
          } );
      });
  </script>
    <!-- Page level plugins -->
  <script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
@endsection