routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'CheckRole:admin']], function () {
    Route::resource('pelatihan', 'PelatihanController');
    // Route::post('pelatihan/{pelatihan}/update', 'PelatihanController@updatedata')->name('updatedata');
    Route::resource('jabatan', 'JabatanController');
    Route::get('pegawai/{id}/hapus', 'PegawaiController@hapus_data');
    Route::resource('pegawai', 'PegawaiController')->except('show');
    Route::resource('peserta', 'PesertaController');
    // Route::post('rekapitulasi/simpan_sementara', 'RekapController@simpan_sementara')->name('rekapitulasi.simpan_sementara');
    Route::get('penilaian/detail', 'PenilaianController@detail_index')->name('penilaian.detail_index');
    Route::get('penilaian/detail/create', 'PenilaianController@detail_create')->name('penilaian.detail_create');
    Route::post('penilaian/detail', 'PenilaianController@detail_store')->name('penilaian.detail_store');
    Route::resource('penilaian', 'PenilaianController');
    Route::get('penilaian/detail/{penilaian}/delete', 'PenilaianController@hapus')->name('penilaian.nilai_hapus');
    Route::get('penilaian/{penilaian}/hapus', 'PenilaianController@hapus_penilaian')->name('penilaian.hapus_penilaian');
    // Route::post('rekapitulasi/update_sementara', 'RekapController@update_sementara')->name('rekapitulasi.update_sementara');
    Route::post('pelatihan/import', 'PelatihanController@import')->name('pelatihan.import');
    Route::resource('agama', 'AgamaController');
    Route::get('pangkat', 'PangkatController@index')->name('pangkat.index');
    Route::get('pangkat/create', 'PangkatController@create')->name('pangkat.create');
    Route::post('pangkat', 'PangkatController@store')->name('pangkat.store');
    Route::delete('pangkat/{pangkat}', 'PangkatController@destroy')->name('pangkat.destroy');
    Route::resource('jenis', 'JenisController');
    Route::resource('lokasi', 'LokasiController');
    // Route::get('/home', 'DashboardController@dashboard')->name('home');
});

Route::group(['middleware' => ['auth', 'CheckRole:admin,staff']], function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-detail','RekapController@nama_penilaian_detail')->name('rekapitulasi.nama_penilaian_detail');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-ket','RekapController@ket_penilaian_detail')->name('rekapitulasi.ket_penilaian_detail');
    Route::get('rekapitulasi/create_nilai', 'RekapController@create_nilai')->name('rekapitulasi.create_nilai');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}', 'RekapController@data_peserta')->name('rekapitulasi.data_peserta');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}/nilai', 'RekapController@data_peserta_show')->name('rekapitulasi.data_peserta_show');
    Route::post('rekapitulasi/simpan_rekap', 'RekapController@simpan_rekap')->name('rekapitulasi.simpan_rekap');
    Route::resource('rekapitulasi', 'RekapController');
    Route::get('laporan/peserta', 'RekapController@index_peserta')->name('rekapitulasi.index_peserta');
    Route::get('laporan', 'RekapController@laporan_index')->name('rekapitulasi.laporan_index');
    Route::get('laporan/peserta/{laporan}/', 'RekapController@laporan')->name('rekapitulasi.laporan');
    Route::get('laporan/pelatihan/{id}/download', 'RekapController@export_pelatihan')->name('rekapitulasi.exportpelatihan');
    Route::get('laporan/{id}/download', 'RekapController@export')->name('rekapitulasi.export');
    Route::post('rekapitulasi/{rekapitulasi}/editnilai', 'ApiController@editnilai');
});

app/Jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    protected $table = "jabatan";
    protected $primaryKey = "id_jabatan";
    protected $fillable = [
        'nama_jabatan', 'ket'
    ];
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use App\Jabatan;
use Validator;
use Illuminate\Http\Request;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_jabatan = Jabatan::all();
        return view ('setting.jabatan.index', [
            'list_jabatan' => $list_jabatan
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('setting.jabatan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $validasi = Validator::make($input, [
            'nama_jabatan' => 'required|min:10|max:100',
            'ket' => 'max:200',
        ]);
        if ($validasi->fails()) {
            return back()->with('warning', $validasi->messages()->all()[0])->withInput();
        }
        Jabatan::create($input);
        return redirect()->route('jabatan.index')->with('toast_success', 'Data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $jabatan_id = Jabatan::find($id);
        $jabatan_id->delete();
        return redirect()->back()->with('toast_success', "Data berhasil dihapus");
    }
}

resources/views/setting/jabatan/create.blade.php
@extends('layouts.template')

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Jabatan Pegawai</h2>
    <div class="row">
        <div class="col-md-6">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('jabatan.index')}}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Kembali</span>
                  </a>
            </div>
            <div class="card-body">
                <form action="{{ route('jabatan.store') }}" method="POST" class="form-horizontal">
                @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <input type="text" class="form-control" name="nama_jabatan" placeholder="Jabatan Pegawai">
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <textarea type="text" class="form-control" name="ket" placeholder="Keterangan" rows="3"></textarea>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary mb-2">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
    @include('sweetalert::alert')
@endsection

resources/views/setting/jabatan/index.blade.php
@extends('layouts.template')

@section('css')

@endsection

@section('content')
    <h2 class="h3 mb-4 text-gray-800">Jabatan Pegawai</h2>
    <div class="row">
        <div class="col-md-8">
            <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a href="{{ route('jabatan.create')}}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-arrow-right"></i>
                    </span>
                    <span class="text">Tambah Data</span>
                  </a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th width="5%">No.</th>
                      <th width="50%">Jabatan</th>
                      <th>Ket.</th>
                      <th width="5%">Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach($list_jabatan as $jabatan)
                        <tr>
                            <th>{{ $loop->iteration }}</th>
                            <th>{{ $jabatan->nama_jabatan }}</th>
                            <th>{{ $jabatan->ket }}</th>
                            <th>
                                <form method="POST" action="{{ route('jabatan.destroy', [$jabatan->id_jabatan]) }}">
                                    @csrf
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                            </th>
                        </tr>
                        @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('js')

@endsection