routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['auth', 'CheckRole:admin']], function () {
    Route::resource('pelatihan', 'PelatihanController');
    // Route::post('pelatihan/{pelatihan}/update', 'PelatihanController@updatedata')->name('updatedata');
    Route::resource('jabatan', 'JabatanController');
    Route::get('pegawai/{id}/hapus', 'PegawaiController@hapus_data');
    Route::resource('pegawai', 'PegawaiController')->except('show');
    Route::resource('peserta', 'PesertaController');
    // Route::post('rekapitulasi/simpan_sementara', 'RekapController@simpan_sementara')->name('rekapitulasi.simpan_sementara');
    Route::get('penilaian/detail', 'PenilaianController@detail_index')->name('penilaian.detail_index');
    Route::get('penilaian/detail/create', 'PenilaianController@detail_create')->name('penilaian.detail_create');
    Route::post('penilaian/detail', 'PenilaianController@detail_store')->name('penilaian.detail_store');
    Route::resource('penilaian', 'PenilaianController');
    Route::get('penilaian/detail/{penilaian}/delete', 'PenilaianController@hapus')->name('penilaian.nilai_hapus');
    Route::get('penilaian/{penilaian}/hapus', 'PenilaianController@hapus_penilaian')->name('penilaian.hapus_penilaian');
    // Route::post('rekapitulasi/update_sementara', 'RekapController@update_sementara')->name('rekapitulasi.update_sementara');
    Route::post('pelatihan/import', 'PelatihanController@import')->name('pelatihan.import');
    Route::resource('agama', 'AgamaController');
    Route::get('pangkat', 'PangkatController@index')->name('pangkat.index');
    Route::get('pangkat/create', 'PangkatController@create')->name('pangkat.create');
    Route::post('pangkat', 'PangkatController@store')->name('pangkat.store');
    Route::delete('pangkat/{pangkat}', 'PangkatController@destroy')->name('pangkat.destroy');
    Route::resource('jenis', 'JenisController');
    Route::resource('lokasi', 'LokasiController');
    // Route::get('/home', 'DashboardController@dashboard')->name('home');
});

Route::group(['middleware' => ['auth', 'CheckRole:admin,staff']], function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-detail','RekapController@nama_penilaian_detail')->name('rekapitulasi.nama_penilaian_detail');
    Route::get('rekapitulasi/{rekapitulasi}/edit/json-ket','RekapController@ket_penilaian_detail')->name('rekapitulasi.ket_penilaian_detail');
    Route::get('rekapitulasi/create_nilai', 'RekapController@create_nilai')->name('rekapitulasi.create_nilai');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}', 'RekapController@data_peserta')->name('rekapitulasi.data_peserta');
    Route::get('rekapitulasi/data_peserta/{rekapitulasi}/nilai', 'RekapController@data_peserta_show')->name('rekapitulasi.data_peserta_show');
    Route::post('rekapitulasi/simpan_rekap', 'RekapController@simpan_rekap')->name('rekapitulasi.simpan_rekap');
    Route::resource('rekapitulasi', 'RekapController');
    Route::get('laporan/peserta', 'RekapController@index_peserta')->name('rekapitulasi.index_peserta');
    Route::get('laporan', 'RekapController@laporan_index')->name('rekapitulasi.laporan_index');
    Route::get('laporan/peserta/{laporan}/', 'RekapController@laporan')->name('rekapitulasi.laporan');
    Route::get('laporan/pelatihan/{id}/download', 'RekapController@export_pelatihan')->name('rekapitulasi.exportpelatihan');
    Route::get('laporan/{id}/download', 'RekapController@export')->name('rekapitulasi.export');
    Route::post('rekapitulasi/{rekapitulasi}/editnilai', 'ApiController@editnilai');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Rekap Nilai') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Rekap Nilai</title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('template/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ asset('template/css/sb-admin-2.min.css') }}" rel="stylesheet">
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  @yield('css')

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon">
          <i class="fas fa-list-ol"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Rekap Nilai <sup>v.1.1</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{{ url('/dashboard') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      @if(Auth::user()->level == 'admin')
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Master
      </div>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item {{ request()->is('pegawai*') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-brain"></i>
          <span>Master Data</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Utilities:</h6>
            <a class="collapse-item {{ request()->is('pegawai*') ? 'active' : '' }}" href="{{ route('pegawai.index')}}">Pegawai</a>
            <a class="collapse-item {{ request()->is('agama*') ? 'active' : '' }}" href="{{ route('agama.index')}}">Agama</a>
            <a class="collapse-item" href="{{ route('pangkat.index')}}">Pangkat</a>
            <a class="collapse-item" href="{{ route('jabatan.index')}}">Jabatan</a>
            <a class="collapse-item" href="{{ route('jenis.index')}}">Jenis Pelatihan</a>
            <a class="collapse-item" href="{{ route('lokasi.index')}}">Lokasi</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item {{ request()->is('penilaian*') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Setting Penilaian</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Utilities:</h6>
            <a class="collapse-item" href="{{ route('penilaian.index')}}">Data Penilaian</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item {{ request()->is('pelatihan*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('pelatihan.index') }}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Pelatihan</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{{ route('rekapitulasi.index') }}">
          <i class="fas fa-fw fa-stream"></i>
          <span>Daftar Nilai Peserta</span></a>
      </li>

      @endif

      <!-- Nav Item - Tables -->
      <li class="nav-item {{ request()->is('laporan*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('rekapitulasi.laporan_index') }}">
          <i class="fas fa-fw fa-sticky-note"></i>
          <span>Laporan Nilai</span></a>
      </li>
      <!-- Nav Item - Tables -->
      <li class="nav-item {{ request()->is('rekapitulasi.create_nilai') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('rekapitulasi.create_nilai') }}">
          <i class="fas fa-fw fa-table"></i>
          <span>Input Nilai</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              {{-- <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div> --}}
              {{-- <label>{{ date('d M Y') }}</label> --}}
              <label>{{ \Carbon\Carbon::now()->locale('id')->isoFormat('LLLL') }}</label>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <div class="mt-4"><label for="">{{ Auth::user()->level }}</label></div>
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                <img class="img-profile rounded-circle" src="{{ asset('img/user.png')}}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                {{-- <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a> --}}
                {{-- <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  {{ Auth::user()->level }}
                </a> --}}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          @yield('content')

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; BPSDM Prov Kaltim {{ \Carbon\Carbon::now()->year }}</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{{ route('logout') }}">Logout</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
            </form>
        </div>
      </div>
    </div>
  </div>
  @include('sweetalert::alert')
  <!-- Bootstrap core JavaScript-->
  <script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>

  @yield('js')

</body>

</html>